version: "1"

services:

  database:
    build:
      context: ./nt-database
    image: nt-database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: notes
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    volumes:
      # - type: bind
        #source: C:\Users\14sur\Documents\work\mysql
      - /home/surup/notes_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306" 
    restart: unless-stopped
    container_name: nt-database

  webserver:
    build: 
      context: ./tomcat-server
    image: tomcat-server
    # mount point for application in tomcat
    volumes:
      - ./tomcat-server/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat-server/tomcat/conf/context.xml:/tmp/context.xml
      # - C:\Users\14sur\Documents\GitHub\key\noteanalyzer\target\notes:/usr/local/tomcat/webapps/notes
      # - C:\tomcatFile\uploadedFile:/opt/tomcat/uploadedFile
      # - C:\tomcatFile\notes:/notes
      # - C:\tomcatFile\unHandlerErrors:/opt/tomcat/unHandlerErrors
      - /home/surup/notes_data/uploadedFile:/opt/tomcat/uploadedFile
      - /home/surup/notes_data/notes:/notes
      - /home/surup/notes_data/unHandlerErrors:/opt/tomcat/unHandlerErrors
    links:
      - database:nt-database
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080" 
      - "8000:8000"
    restart: always
  
  import-script:
    build: 
      context: /home/surup/github/old_import/nt_import
    image: import-script
    volumes:
      # - C:\tomcatFile\uploadedFile:/opt/tomcat/uploadedFile
      # - C:\tomcatFile\notes:/notes
      # - C:\tomcatFile\unHandlerErrors:/opt/tomcat/unHandlerErrors
      - /home/surup/notes_data:/opt/tomcat
      - /home/surup/notes_data/notes:/notes 
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        # - C:\tomcatFile\rabbitmq\data\:/var/lib/rabbitmq/
        # - C:\tomcatFile\rabbitmq\log\:/var/log/rabbitmq
        - /home/surup/notes_data/rabbitmq/data/:/var/lib/rabbitmq/
        - /home/surup/notes_data/rabbitmq/log/:/var/log/rabbitmq
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    restart: unless-stopped
  
  restntimport:
    build: 
      context: /home/surup/github/nt_import/api
      target: prod
    image: restntimport
    # environment:
    #   - FLASK_DEBUG=1
    # entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "webapp",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0", "-p", "5002" ]
    volumes:
      # - C:\tomcatFile\uploadedFile:/app/uploadedFile
      # - C:\Users\14sur\Documents\GitHub\nt_import\api:/work
      - /home/surup/notes_data/uploadedFile:/app/uploadedFile
      - /home/surup/github/nt_import/api:/work
    links:
      - database:nt-database
      - rabbitmq:nt-rabbitmq
    ports:
      - 5002:5002
      # - 5678:5678
    restart: unless-stopped

  flaskapi:
    build: 
        context: /home/surup/github/api
    image: flaskapi
    volumes:
      - /home/surup/github/api:/app
    ports:
      - 5001:5000
    restart: unless-stopped

  vue-js:
    build: 
        context: /home/surup/github/VueJs
    image: vue-js
    ports:
      - 8081:80
    restart: unless-stopped

